// Galería de productos. Cada pieza lleva foto (solo producto, sin modelos),
// marca, valoración de 1 a 5 estrellas, tu opinión y con qué combinarla.
//
// LEGAL: todas las fotos son de Unsplash, con licencia libre para uso comercial
// sin necesidad de permiso (https://unsplash.com/license). Cada pieza guarda el
// enlace a la foto original como crédito. No uses fotos de las webs de las
// marcas sin su permiso: tienen copyright.
//
// Para añadir una pieza: copia un bloque y cambia el `slug` (único, sin espacios).
// La foto puede ser:
//   - de Unsplash: `foto: "photo-..."` (el id de la URL de la imagen) y
//     `credito: "https://unsplash.com/photos/..."` (la página de la foto), o
//   - propia: `foto: "/galeria/<archivo>.jpg"` guardada en `public/galeria/`.
// Si la marca no se ve en la foto, escribe "Marca no identificada".

export type TipoPieza =
  | "Vestidos"
  | "Abrigos y chaquetas"
  | "Camisas y tops"
  | "Punto"
  | "Vaqueros"
  | "Zapatillas"
  | "Zapatos y botas"
  | "Bolsos"
  | "Accesorios"
  | "Joyas y relojes";

export type Pieza = {
  slug: string;
  nombre: string;
  marca: string;
  tipo: TipoPieza;
  foto: string;
  credito?: string;
  valoracion: 1 | 2 | 3 | 4 | 5;
  opinion: string;
  combina: string;
  destacada?: boolean;
};

export const tipos: TipoPieza[] = [
  "Vestidos",
  "Abrigos y chaquetas",
  "Camisas y tops",
  "Punto",
  "Vaqueros",
  "Zapatillas",
  "Zapatos y botas",
  "Bolsos",
  "Accesorios",
  "Joyas y relojes",
];

// URL de la imagen: Unsplash (id "photo-...") o archivo propio en /public.
export function urlFoto(foto: string, ancho = 1200) {
  if (foto.startsWith("photo-")) {
    return `https://images.unsplash.com/${foto}?auto=format&fit=crop&w=${ancho}&q=75`;
  }
  return foto;
}

const U = "https://unsplash.com/photos/";

export const piezas: Pieza[] = [
  // ───────────── Vestidos ─────────────
  {
    slug: "vestido-encaje-blanco",
    nombre: "Vestido de encaje blanco",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1591221662157-6f62de5508eb",
    credito: U + "white-floral-lace-sleeveless-dress-B_P6nONZk58",
    valoracion: 4,
    opinion: "El encaje en blanco roto tiene un aire romántico que no cae en lo cursi si el corte es sencillo. Sin mangas y sin volumen, es un vestido de día que vale para una boda de mañana.",
    combina: "Sandalia plana de piel natural, bolso de rafia y pendientes dorados pequeños. Para la noche, salón nude.",
    destacada: true,
  },
  {
    slug: "vestido-floral-azul",
    nombre: "Vestido floral azul",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1760097679488-f808c6aca11d",
    credito: U + "blue-floral-dress-hanging-on-a-rack-outdoors-clothesline-2EKY6Nrm6cQ",
    valoracion: 4,
    opinion: "Un estampado floral pequeño sobre fondo azul es de los pocos que funcionan de la primavera al otoño. La tela ligera y la manga corta lo hacen muy fácil de llevar.",
    combina: "Cazadora vaquera encima, zapatilla blanca de piel y bandolera pequeña en marrón o crudo.",
  },

  // ───────────── Abrigos y chaquetas ─────────────
  {
    slug: "chaqueta-cuero-negra",
    nombre: "Chaqueta de cuero negra",
    marca: "Marca no identificada",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1727515546577-f7d82a47b51d",
    credito: U + "a-black-leather-jacket-laying-on-top-of-a-bed-YehJ089r0uY",
    valoracion: 5,
    opinion: "La chaqueta de cuero negra es la única prenda que endurece cualquier look sin esfuerzo. Si es de piel de verdad, mejora con los años y no pasa de moda.",
    combina: "Vestido floral para contrastar, vaquero recto y camiseta blanca, o encima de un vestido negro de noche.",
    destacada: true,
  },
  {
    slug: "cazadora-vaquera",
    nombre: "Cazadora vaquera",
    marca: "Marca no identificada",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1580644228275-2b826dbec5bf",
    credito: U + "blue-denim-button-up-jacket-yPJeQRCeOdk",
    valoracion: 4,
    opinion: "La cazadora vaquera clásica, en azul medio y sin lavados agresivos, es el abrigo de entretiempo que nunca sobra en el armario.",
    combina: "Vestido de flores, falda midi negra o pantalón de lino claro. Evita combinarla con vaquero del mismo tono.",
  },
  {
    slug: "chaqueta-tommy-hilfiger",
    nombre: "Cortavientos colorblock",
    marca: "Tommy Jeans",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1711527124424-463764d8d8e5",
    credito: U + "a-jacket-hanging-on-a-coat-rack-in-a-room-C1-PIlyLvD8",
    valoracion: 4,
    opinion: "El cortavientos en bloques de color azul marino, blanco y naranja es puro estilo años noventa, y Tommy Jeans lo hace mejor que nadie. Ligero, con capucha y muy reconocible.",
    combina: "Vaquero recto claro, camiseta blanca y zapatilla retro. El resto del look, liso: la chaqueta ya tiene color de sobra.",
  },
  {
    slug: "chaqueta-negra-tommy",
    nombre: "Chaqueta negra con etiqueta",
    marca: "Tommy Jeans",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1711452961300-86b759eb25c3",
    credito: U + "a-tommy-hilfiger-label-on-a-black-jacket-d-h3agdG8IA",
    valoracion: 3,
    opinion: "Correcta y discreta. Una chaqueta negra de nailon que cumple, aunque el precio se paga por la etiqueta más que por el diseño.",
    combina: "Todo en negro con zapatilla blanca, o vaquero claro y camiseta gris.",
  },

  // ───────────── Camisas y tops ─────────────
  {
    slug: "camisa-blanca-percha",
    nombre: "Básicos blancos de algodón",
    marca: "Marca no identificada",
    tipo: "Camisas y tops",
    foto: "photo-1605450081927-6b40c11c661f",
    credito: U + "white-button-up-long-sleeve-shirt-sYLP-Hitwkk",
    valoracion: 5,
    opinion: "Camisas, blusas y vestidos blancos de algodón: la base de cualquier armario de verano. Mejor en blanco roto que en blanco óptico, y en tejidos con cuerpo que no transparenten.",
    combina: "Con todo: vaquero, falda de lunares, pantalón de vestir o encima del bikini como vestido de playa.",
    destacada: true,
  },
  {
    slug: "top-negro-sin-mangas",
    nombre: "Top negro sin mangas",
    marca: "Marca no identificada",
    tipo: "Camisas y tops",
    foto: "photo-1519554318711-aaf73ece6ff9",
    credito: U + "black-sleeveless-top-hanging-on-wardrobe-cp-VMJ-mdKs",
    valoracion: 3,
    opinion: "Un básico que necesita buena tela para no parecer ropa interior. Si es de viscosa o seda con caída, vale para la oficina; si es de punto fino, mejor solo para casa.",
    combina: "Pantalón ancho de pinzas y sandalia de tacón, o vaquero de tiro alto y blazer.",
  },
  {
    slug: "polo-lacoste-rojo",
    nombre: "Polo rojo",
    marca: "Lacoste",
    tipo: "Camisas y tops",
    foto: "photo-1707578579055-1e327f62c047",
    credito: U + "a-close-up-of-a-red-polo-shirt-with-a-green-alligator-embroidered-on-it-oihGFVX91_g",
    valoracion: 4,
    opinion: "El polo de piqué de Lacoste es un clásico por algo: el tejido aguanta cientos de lavados y el corte no ha cambiado en décadas. En rojo, ilumina.",
    combina: "Falda plisada blanca, short vaquero o pantalón chino beige. Zapatilla blanca siempre.",
  },
  {
    slug: "sudadera-champion-azul",
    nombre: "Sudadera azul con capucha",
    marca: "Champion",
    tipo: "Camisas y tops",
    foto: "photo-1641377061384-61e0ce81f717",
    credito: U + "a-close-up-of-a-blue-hoodie-with-a-tag-on-it-wJtHMgXP3-4",
    valoracion: 3,
    opinion: "Champion hace sudaderas gruesas y bien cosidas, pero el logo grande cansa. Mejor los modelos con el logo pequeño en la manga.",
    combina: "Pantalón de chándal a juego para casa, o vaquero recto y abrigo largo de lana para elevarla.",
  },

  // ───────────── Punto ─────────────
  {
    slug: "jersey-punto-trenzado",
    nombre: "Jersey de punto trenzado",
    marca: "Marca no identificada",
    tipo: "Punto",
    foto: "photo-1601379327928-bedfaf9da2d0",
    credito: U + "white-and-brown-knit-textile-Ds4TsdS095U",
    valoracion: 4,
    opinion: "El punto de ochos en color crudo es abrigo y textura a la vez. Busca lana o mezcla con lana; el acrílico puro hace bolitas en un mes.",
    combina: "Vaquero claro para un look monocromo, o falda de cuero negra para contrastar.",
  },
  {
    slug: "jersey-crudo-canale",
    nombre: "Jersey crudo de canalé",
    marca: "Marca no identificada",
    tipo: "Punto",
    foto: "photo-1574201635302-388dd92a4c3f",
    credito: U + "person-wearing-grey-knit-sweater-mU88MlEFcoU",
    valoracion: 4,
    opinion: "Crudo, de canalé, con el cuello ligeramente alto. Es el jersey que combina con todo y que, si es de buena lana, dura toda la vida.",
    combina: "Pantalón de pana marrón, abrigo camel y bota de piel. También con vaquero negro.",
    destacada: true,
  },
  {
    slug: "pila-jerseis-lana",
    nombre: "Jerséis de lana en tonos neutros",
    marca: "Marca no identificada",
    tipo: "Punto",
    foto: "photo-1643015862949-5c8d15a4242e",
    credito: U + "a-pile-of-sweaters-sitting-next-to-each-other-NPPlYOnhBuQ",
    valoracion: 3,
    opinion: "Una pila de jerséis en beige, gris y crudo es la base de un armario de invierno. Mejor tres buenos que diez de colores que no combinan.",
    combina: "Entre ellos: capas de punto fino bajo punto grueso, siempre en la misma gama de color.",
  },

  // ───────────── Vaqueros ─────────────
  {
    slug: "vaquero-levis-azul",
    nombre: "Vaquero azul clásico",
    marca: "Levi's",
    tipo: "Vaqueros",
    foto: "photo-1619471327033-3fb3b2b0d966",
    credito: U + "blue-levis-denim-bottoms-4v1cMdT1480",
    valoracion: 5,
    opinion: "El 501 de Levi's es el vaquero recto original. Tiro alto, pierna recta, tela rígida que se amolda con el uso. No hay vaquero más seguro.",
    combina: "Camisa blanca por dentro con cinturón fino, camiseta y chaqueta de cuero, o jersey de punto grueso.",
    destacada: true,
  },
  {
    slug: "vaquero-levis-detalle",
    nombre: "Vaquero azul con etiqueta",
    marca: "Levi's",
    tipo: "Vaqueros",
    foto: "photo-1601278085511-992ec3000c8a",
    credito: U + "blue-levis-denim-bottoms-HMeSiGy4aQE",
    valoracion: 4,
    opinion: "Lavado medio, sin rotos. Es el tono más fácil de combinar y el que menos pasa de moda; los lavados muy claros o muy oscuros dependen más de la temporada.",
    combina: "Zapatilla blanca y camiseta gris para el día; salón nude y blusa de seda para la noche.",
  },
  {
    slug: "vaqueros-tres-tonos",
    nombre: "Vaqueros en tres lavados",
    marca: "Marca no identificada",
    tipo: "Vaqueros",
    foto: "photo-1542272604-787c3835535d",
    credito: U + "three-assorted-color-denim-bottoms-m1m2EZOZVwA",
    valoracion: 4,
    opinion: "Claro, medio y oscuro: con tres vaqueros de la misma horma tienes resuelto el año. El oscuro para vestir, el medio para diario, el claro para verano.",
    combina: "Cada uno con lo mismo de arriba: el tono del vaquero cambia el registro del look sin cambiar nada más.",
  },

  // ───────────── Zapatillas ─────────────
  {
    slug: "nike-air-max-roja",
    nombre: "Air Max 270 roja",
    marca: "Nike",
    tipo: "Zapatillas",
    foto: "photo-1542291026-7eec264c27ff",
    credito: U + "unpaired-red-nike-sneaker-164_6wVEHfI",
    valoracion: 4,
    opinion: "Una zapatilla de color es la forma más barata de tener un look con carácter. La Air Max 270 es cómoda, con una cámara de aire visible que le da presencia.",
    combina: "Todo negro o todo gris: mallas, sudadera y abrigo neutro para que la zapatilla sea la protagonista.",
  },
  {
    slug: "nike-verde-negra",
    nombre: "Zapatilla running verde y negra",
    marca: "Nike",
    tipo: "Zapatillas",
    foto: "photo-1606107557195-0e29a4b5b4aa",
    credito: U + "green-and-black-nike-athletic-shoe-kP6knT7tjn4",
    valoracion: 3,
    opinion: "Para correr, muy bien. Para vestir, el verde flúor es difícil: solo funciona si el resto del look es completamente neutro.",
    combina: "Ropa deportiva negra. Fuera del gimnasio, mejor elegir otro color.",
  },
  {
    slug: "nike-blanca-roja",
    nombre: "Zapatilla blanca y naranja",
    marca: "Nike",
    tipo: "Zapatillas",
    foto: "photo-1600185365483-26d7a4cc7519",
    credito: U + "white-and-red-nike-athletic-shoe-J2-wAQDckus",
    valoracion: 4,
    opinion: "Blanca con un toque de naranja: deportiva pero fácil de combinar. El swoosh de color da vida sin condicionar todo el look.",
    combina: "Vaquero azul medio, camiseta blanca y cazadora vaquera. También con falda vaquera.",
  },
  {
    slug: "nike-air-force-negra",
    nombre: "Air Force 1 negra de piel",
    marca: "Nike",
    tipo: "Zapatillas",
    foto: "photo-1543508282-6319a3e2621f",
    credito: U + "black-leather-sneaker-on-white-desk-PqbL_mxmaUE",
    valoracion: 5,
    opinion: "La Air Force 1 negra con el swoosh blanco es de las zapatillas más fáciles de vestir: piel, suela gruesa y solo dos colores. Se limpia con un paño.",
    combina: "Vestido negro con medias, pantalón cargo, vaquero de cualquier tono. Va con todo lo que no sea muy formal.",
    destacada: true,
  },
  {
    slug: "adidas-negras-blancas",
    nombre: "Superstar negra",
    marca: "adidas",
    tipo: "Zapatillas",
    foto: "photo-1593287073863-c992914cb3e3",
    credito: U + "black-and-white-adidas-sneakers-XwWGyrVidZE",
    valoracion: 4,
    opinion: "Las tres bandas blancas sobre negro son un clásico de adidas que funciona igual con chándal que con vaquero. Suela plana, muy cómoda para andar.",
    combina: "Pantalón de chándal negro con abrigo largo, o vaquero recto y camiseta blanca.",
  },
  {
    slug: "adidas-rojas-blancas",
    nombre: "Campus roja",
    marca: "adidas",
    tipo: "Zapatillas",
    foto: "photo-1621665422246-fde75fb7e7f5",
    credito: U + "red-and-white-adidas-low-top-sneakers-7irKimCkk6g",
    valoracion: 3,
    opinion: "Bonitas, pero el rojo entero pide un armario neutro para no chocar. Son más de capricho que de fondo de armario.",
    combina: "Vaquero blanco o azul claro y camiseta blanca. Nada más de color.",
  },
  {
    slug: "converse-marrones-altas",
    nombre: "Chuck Taylor altas beige",
    marca: "Converse",
    tipo: "Zapatillas",
    foto: "photo-1556048219-bb6978360b84",
    credito: U + "brown-converse-high-top-shoes-YQbJLyY0hFU",
    valoracion: 4,
    opinion: "Las Converse altas en beige son una alternativa a las negras de siempre: más suaves y menos vistas. La bota alta cubre el tobillo y sienta bien con falda.",
    combina: "Falda midi de punto, vestido camisero o vaquero remangado. Con calcetín blanco a la vista.",
    destacada: true,
  },
  {
    slug: "vans-sk8-hi-cuadros",
    nombre: "Sk8-Hi de cuadros",
    marca: "Vans",
    tipo: "Zapatillas",
    foto: "photo-1626379530580-6a58c5cf1d5e",
    credito: U + "black-and-white-converse-all-star-low-tops-cv6ayjDOZog",
    valoracion: 3,
    opinion: "El tablero de ajedrez de Vans es un icono, pero manda mucho: el resto del look tiene que ser liso. En bota alta abriga más el tobillo y tiene más presencia que la Slip-On.",
    combina: "Vaquero negro o pantalón cargo y camiseta lisa. Nada más estampado.",
  },
  {
    slug: "louis-vuitton-zapatilla-monogram",
    nombre: "Zapatilla con monogram",
    marca: "Louis Vuitton",
    tipo: "Zapatillas",
    foto: "photo-1629439612315-b69e9236c8e1",
    credito: U + "black-and-white-checkered-vans-low-top-sneakers-im4ewz-fytc",
    valoracion: 3,
    opinion: "Una zapatilla de lujo con el monogram entero es más un objeto que un calzado. Bien hecha, sin duda, pero por ese precio hay diez zapatillas más fáciles de llevar.",
    combina: "Todo en negro o en crudo. El logo ya hace todo el ruido que hace falta.",
  },
  {
    slug: "new-balance-rosa-gris",
    nombre: "Zapatilla rosa y gris",
    marca: "New Balance",
    tipo: "Zapatillas",
    foto: "photo-1551107696-a4b0c5a0d9a2",
    credito: U + "pinkgreyand-white-new-balance-sneaker-ezdrvzA1hZw",
    valoracion: 4,
    opinion: "New Balance ha convertido la zapatilla 'de padre' en la más deseada, y con razón: son cómodas y los colores apagados combinan mejor que los brillantes.",
    combina: "Pantalón de pinzas gris, camiseta blanca y gabardina. También con vestido de punto.",
  },
  {
    slug: "lacoste-zapatillas",
    nombre: "Zapatilla verde de ante",
    marca: "Lacoste",
    tipo: "Zapatillas",
    foto: "photo-1718882703813-5b18d074242a",
    credito: U + "a-pair-of-lacoste-shoes-sitting-on-top-of-a-white-chair-EtJO5VH6ID8",
    valoracion: 3,
    opinion: "Zapatilla baja de ante verde botella con suela blanca. El verde oscuro es casi un neutro y se lleva mejor de lo que parece. Un poco más cara que otras equivalentes por la marca.",
    combina: "Vaquero claro, pantalón chino beige o falda vaquera. Con blanco y crudo queda especialmente bien.",
  },

  // ───────────── Zapatos y botas ─────────────
  {
    slug: "dr-martens-1460-negras",
    nombre: "Bota 1460 negra",
    marca: "Dr. Martens",
    tipo: "Zapatos y botas",
    foto: "photo-1747083996241-3d86d9dbab11",
    credito: U + "black-dr-martens-boots-are-on-a-white-surface-fq_ZFTLoxhA",
    valoracion: 5,
    opinion: "La 1460 de ocho ojales es la bota más versátil que hay: va con vestido, con vaquero y con falda. Duras de domar las primeras semanas, indestructibles después.",
    combina: "Vestido floral con medias negras, vaquero remangado o falda midi de cuero.",
    destacada: true,
  },
  {
    slug: "botas-cordones-negras",
    nombre: "Bota negra de cordones",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1616610868156-fe7e276de965",
    credito: U + "black-leather-lace-up-boots-fK33vAmHYvE",
    valoracion: 4,
    opinion: "Una bota negra de cordones con suela gruesa es el calzado de invierno más útil. Abriga, aguanta la lluvia y viste todo lo que lleves encima.",
    combina: "Abrigo largo de lana, vaquero recto y jersey de cuello alto.",
  },
  {
    slug: "birkenstock-arizona",
    nombre: "Sandalia Arizona",
    marca: "Birkenstock",
    tipo: "Zapatos y botas",
    foto: "photo-1603487742131-4160ec999306",
    credito: U + "brown-and-gray-slide-sandals-WzncgWs3RJ4",
    valoracion: 4,
    opinion: "La Arizona de dos hebillas ya no es solo cómoda: es un clásico. En ante topo o marrón combina mejor que en negro para el verano.",
    combina: "Pantalón de lino, vestido largo de algodón, falda vaquera. Con calcetín, solo si te atreves.",
  },
  {
    slug: "sandalias-negras-piel",
    nombre: "Sandalia negra de piel",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1596523027665-9da35ced2388",
    credito: U + "black-leather-open-toe-sandals-LnR6-7P2YNk",
    valoracion: 4,
    opinion: "Sandalia plana negra de piel con plantilla anatómica. Es la más fácil de vestir de todas las planas: va con colores claros y con oscuros.",
    combina: "Vestido negro de lino, pantalón blanco ancho, falda midi de cualquier color.",
  },
  {
    slug: "timberland-grises",
    nombre: "Bota de trabajo gris",
    marca: "Timberland",
    tipo: "Zapatos y botas",
    foto: "photo-1520472475098-8e72973f5462",
    credito: U + "person-wearing-pair-of-gray-timberland-work-boots-MtTp6mfSHJk",
    valoracion: 3,
    opinion: "La Timberland en gris es más discreta que la amarilla clásica, pero sigue siendo una bota pesada. Para el campo o la nieve, bien; para la ciudad, hay opciones más ligeras.",
    combina: "Vaquero recto, parka y jersey de lana gorda. Look de fin de semana en el campo.",
  },
  {
    slug: "botas-trabajo-beige",
    nombre: "Bota de trabajo beige",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1554133818-7bb790d55236",
    credito: U + "pair-of-brown-and-black-work-boots-on-green-grass-field-during-daytime-B1Sn_ADEohs",
    valoracion: 3,
    opinion: "Bota robusta de nobuk beige con suela gruesa. Abriga, dura y el color claro la hace más urbana que la clásica amarilla, aunque se ensucia antes.",
    combina: "Vaquero azul remangado, jersey de punto crudo y parka verde oliva.",
  },
  {
    slug: "ugg-clasica-marron",
    nombre: "Bota clásica de borrego",
    marca: "UGG",
    tipo: "Zapatos y botas",
    foto: "photo-1586810679476-7e2e76421009",
    credito: U + "brown-and-white-fur-boots-rlKUNyHUPGc",
    valoracion: 3,
    opinion: "Calientes como ninguna otra bota. El problema es que son casi una zapatilla de estar por casa: fuera, solo con un look muy pensado.",
    combina: "Mallas negras, jersey oversize y abrigo largo de pelo. Nunca con vaquero por dentro.",
  },
  {
    slug: "salones-nude",
    nombre: "Salón nude",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1535043934128-cf0b28d52f95",
    credito: U + "white-textured-high-heeled-pumps-Zx76sbAndc0",
    valoracion: 4,
    opinion: "El salón en tono piel alarga la pierna más que cualquier otro color porque no la corta. Es el zapato de tacón más útil que se puede tener.",
    combina: "Vestido de cualquier color, pantalón de vestir tobillero, vaquero oscuro con blusa.",
  },
  {
    slug: "salones-floral",
    nombre: "Salón estampado floral",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1543163521-1bf539c55dd2",
    credito: U + "pair-of-blue-and-pink-floral-almond-toe-pumps-E-0ON3VGrBc",
    valoracion: 3,
    opinion: "Un zapato estampado es un acento, no una base. Divertidos para una boda o una cena, pero no esperes ponértelos cada semana.",
    combina: "Vestido liso en azul marino o crudo. Nada más con estampado.",
  },
  {
    slug: "stiletto-blanco",
    nombre: "Stiletto blanco de punta",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1562687848-c1664eff566d",
    credito: U + "white-leather-pointed-toe-stiletto-BI9NjChWn6s",
    valoracion: 4,
    opinion: "El stiletto blanco es más moderno que el negro y más elegante que el de color. Pide cuidado, pero pocas cosas visten tanto un look sencillo.",
    combina: "Vestido negro de noche, traje pantalón blanco o vaquero recto con camisa.",
  },
  {
    slug: "botas-marron-piel",
    nombre: "Botín de piel marrón",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1605733160314-4fc7dac4bb16",
    credito: U + "a-close-up-of-a-pair-of-brown-boots-3OZr-hLbsq0",
    valoracion: 4,
    opinion: "El botín marrón de piel mejora con los años. Merece la pena pagar más por uno que se pueda resolar.",
    combina: "Vaquero azul, vestido de punto camel o falda midi con medias tupidas.",
  },
  {
    slug: "botas-slouch-negras",
    nombre: "Bota slouch negra",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1763661300203-aa3e2702f510",
    credito: U + "a-pair-of-black-leather-slouch-boots-tDHBHyAO-Hw",
    valoracion: 4,
    opinion: "La caña arrugada da un aire relajado que la bota rígida no tiene. Cubren la pierna y suavizan cualquier look.",
    combina: "Falda midi, vestido de punto o vaquero pitillo por dentro.",
  },
  {
    slug: "botin-negro-blanco",
    nombre: "Botín negro de piel",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1605732440685-d0654d81aa30",
    credito: U + "black-leather-boot-on-white-table-KKsB-eOAjVo",
    valoracion: 4,
    opinion: "Botín negro liso, sin adornos, con tacón bajo. Es el zapato de invierno que va con todo y no se nota, que es justo lo que se le pide.",
    combina: "Vaquero, pantalón de vestir, vestido con medias. Todo.",
  },

  // ───────────── Bolsos ─────────────
  {
    slug: "gucci-marmont-negro",
    nombre: "Bolso Marmont negro",
    marca: "Gucci",
    tipo: "Bolsos",
    foto: "photo-1548036328-c9fa89d128fa",
    credito: U + "black-gucci-leather-shoulder-bag-ZmeFtu11Hpc",
    valoracion: 5,
    opinion: "Negro, acolchado y con cadena. El Marmont hace que el look más sencillo parezca pensado, y se lleva igual de día que de noche. Caro, pero con reventa.",
    combina: "Vaquero y camiseta blanca para bajarlo, vestido negro para subirlo.",
    destacada: true,
  },
  {
    slug: "louis-vuitton-monogram",
    nombre: "Bolso Monogram",
    marca: "Louis Vuitton",
    tipo: "Bolsos",
    foto: "photo-1691480288782-142b953cf664",
    credito: U + "a-brown-and-tan-louis-vuitton-bag-glY1L-eo0Fc",
    valoracion: 4,
    opinion: "El monogram es el estampado más reconocible de la moda. Eso es una virtud y un defecto: hay que combinarlo con ropa muy sencilla para que no parezca demasiado.",
    combina: "Gabardina beige, camiseta blanca y vaquero. Colores neutros y nada más con logo.",
  },
  {
    slug: "louis-vuitton-baul",
    nombre: "Baúl y bolso de mano",
    marca: "Louis Vuitton",
    tipo: "Bolsos",
    foto: "photo-1698912208639-1344837921e4",
    credito: U + "a-louis-vuitton-trunk-with-a-handbag-on-top-of-it-oco2KcKei_U",
    valoracion: 3,
    opinion: "Louis Vuitton empezó haciendo baúles, y se nota en la calidad. El bolso de mano pequeño es precioso, pero cabe poco: es para salir, no para el día a día.",
    combina: "Vestido de noche liso y zapato de tacón fino.",
  },
  {
    slug: "michael-kors-rayas",
    nombre: "Bolso de rayas",
    marca: "Michael Kors",
    tipo: "Bolsos",
    foto: "photo-1751522949283-293763ee6f2a",
    credito: U + "a-striped-michael-kors-purse-is-pictured-v_praOEpVcI",
    valoracion: 3,
    opinion: "Michael Kors hace bolsos correctos a precio medio. Las rayas dan un aire de verano, aunque limitan el uso al resto del año.",
    combina: "Vestido blanco de lino, sandalia plana y gafas de sol.",
  },
  {
    slug: "michael-kors-detalle",
    nombre: "Bolso de piel con logo",
    marca: "Michael Kors",
    tipo: "Bolsos",
    foto: "photo-1712253600760-0536ce3f2f85",
    credito: U + "a-close-up-of-a-michael-kors-bag-yNL7hL03hBs",
    valoracion: 4,
    opinion: "Piel granulada, herrajes dorados y logo discreto. Un bolso de diario resistente que no desentona en la oficina.",
    combina: "Blazer, camisa blanca y pantalón de pinzas. Con salón nude, look de trabajo completo.",
  },
  {
    slug: "coach-marron",
    nombre: "Bolso de piel marrón",
    marca: "Coach",
    tipo: "Bolsos",
    foto: "photo-1712253600732-baa27bf3c012",
    credito: U + "a-close-up-of-a-brown-coach-purse-j3eR880Py10",
    valoracion: 4,
    opinion: "Coach trabaja muy bien la piel a un precio más razonable que las marcas europeas. El marrón envejece con gracia y combina con más cosas de las que parece.",
    combina: "Vaquero azul, camisa blanca y botín marrón. También con vestido camel.",
  },
  {
    slug: "coach-tote-tigre",
    nombre: "Tote con estampado de tigre",
    marca: "Coach",
    tipo: "Bolsos",
    foto: "photo-1751522917613-68281b131e45",
    credito: U + "a-coach-tote-bag-with-a-tiger-design-dwT7uM1fuVQ",
    valoracion: 3,
    opinion: "Un tote grande y con un estampado llamativo. Práctico para el día, pero el dibujo manda tanto que solo lo pondría con ropa muy lisa.",
    combina: "Todo en negro o en crudo. Zapatilla blanca.",
  },
  {
    slug: "bolso-piel-trenzada",
    nombre: "Bolso de piel trenzada",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1598532163257-ae3c6b2524b6",
    credito: U + "brown-leather-handbag-on-white-surface-tcVH_BwHtrc",
    valoracion: 5,
    opinion: "Un bolso de piel de calidad, sin logos, es la mejor compra de accesorios que se puede hacer. El trenzado le da textura y envejece muy bien.",
    combina: "Vestido de lino, pantalón blanco o vaquero claro. Colores cálidos: crudo, camel, verde oliva.",
    destacada: true,
  },
  {
    slug: "bolso-rojo-asa",
    nombre: "Bolso rojo con asa",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1584917865442-de89df76afd3",
    credito: U + "red-leather-handbag-on-white-table-oCXVxwTFwqE",
    valoracion: 4,
    opinion: "El bolso es el sitio más fácil para meter color: no toca la piel, no depende de la talla y se cambia en un segundo. En rojo, ilumina cualquier look neutro.",
    combina: "Gabardina beige y vaquero, o vestido negro. Zapato negro o nude, nunca rojo también.",
  },
  {
    slug: "bandolera-rosa",
    nombre: "Bandolera rosa",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1566150905458-1bf1fc113f0d",
    credito: U + "pink-leather-crossbody-bag-APNnyM36puU",
    valoracion: 3,
    opinion: "Pequeña, cruzada y de color. Para el día a día no hace falta más, aunque el rosa empolvado pide un armario en tonos neutros.",
    combina: "Gris, crudo, beige y blanco. Con vaquero claro queda muy bien.",
  },
  {
    slug: "fjallraven-kanken-roja",
    nombre: "Mochila Kånken burdeos",
    marca: "Fjällräven",
    tipo: "Bolsos",
    foto: "photo-1671628031185-8ac6a3b29ed6",
    credito: U + "a-red-backpack-sitting-on-top-of-a-wooden-table-ugrBzscARXc",
    valoracion: 4,
    opinion: "La Kånken es fea a propósito, y por eso funciona. Ligera, cuadrada, resistente al agua, y el burdeos es más fácil de combinar que los colores vivos.",
    combina: "Gabardina, vaquero y zapatilla blanca. Look de ciudad para ir a todas partes andando.",
  },
  {
    slug: "bolso-negro-herrajes",
    nombre: "Bolso negro con herrajes plateados",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1614179689702-355944cd0918",
    credito: U + "black-leather-handbag-on-white-bed-CtOA9wbFAdQ",
    valoracion: 4,
    opinion: "Negro con herrajes plateados en lugar de dorados: más discreto y más moderno. Un bolso estructurado que vale para la oficina y para una cena.",
    combina: "Gris, azul marino y blanco. Con zapato negro o plateado.",
  },
  {
    slug: "bolso-gris-hebillas",
    nombre: "Satchel gris con hebillas doradas",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1605733513597-a8f8341084e6",
    credito: U + "grey-leather-satchel-with-gold-buckles-J4DnKxz_3sA",
    valoracion: 4,
    opinion: "El gris es el color de bolso más infravalorado: combina con negro y con marrón, cosa que ninguno de los dos hace entre sí.",
    combina: "Abrigo camel, vaquero oscuro, jersey negro. También con vestido azul marino.",
  },

  // ───────────── Accesorios ─────────────
  {
    slug: "ray-ban-wayfarer",
    nombre: "Gafas Wayfarer negras",
    marca: "Ray-Ban",
    tipo: "Accesorios",
    foto: "photo-1572635196237-14b3f281503f",
    credito: U + "shallow-focus-photo-of-black-ray-ban-wayfarer-sunglasses-K62u25Jk6vo",
    valoracion: 5,
    opinion: "La Wayfarer lleva desde los años cincuenta siendo la gafa de sol más copiada del mundo. Favorece a casi todas las caras y va con todo.",
    combina: "Con cualquier cosa. Es el accesorio que más cambia un look por menos esfuerzo.",
    destacada: true,
  },
  {
    slug: "ray-ban-negras",
    nombre: "Gafas de sol negras",
    marca: "Ray-Ban",
    tipo: "Accesorios",
    foto: "photo-1556306535-38febf6782e7",
    credito: U + "black-ray-ban-sunglasses-D3n859qG03U",
    valoracion: 4,
    opinion: "Montura negra clásica de pasta. Si no sabes qué gafas comprar, compra estas: no se equivocan.",
    combina: "Todo. Con looks claros de verano quedan especialmente bien.",
  },
  {
    slug: "boina-roja",
    nombre: "Boina roja",
    marca: "Marca no identificada",
    tipo: "Accesorios",
    foto: "photo-1778865575946-4d26642a0323",
    credito: U + "red-beret-displayed-on-a-black-mannequin-head-C99z974RPng",
    valoracion: 4,
    opinion: "La boina es el sombrero más fácil de llevar: no tapa la cara, cabe en el bolso y da un aire francés a cualquier abrigo. En rojo, es el acento de todo el look.",
    combina: "Gabardina beige o abrigo negro, jersey de rayas y vaquero. Nada más rojo.",
  },
  {
    slug: "cinturones-piel-marron",
    nombre: "Cinturones de piel marrón",
    marca: "Marca no identificada",
    tipo: "Accesorios",
    foto: "photo-1711443982852-b3df5c563448",
    credito: U + "a-pair-of-brown-leather-belts-sitting-on-top-of-a-white-piece-of-paper-rH16wMV8ImM",
    valoracion: 4,
    opinion: "Un cinturón fino de piel marrón es lo que convierte un vaquero y una camisa en un look. Hebilla pequeña, piel de verdad, sin logos.",
    combina: "Camisa por dentro del vaquero, vestido camisero, pantalón de pinzas. Con zapato marrón a juego.",
  },

  // ───────────── Joyas y relojes ─────────────
  {
    slug: "pendientes-cristal",
    nombre: "Pendientes de cristal",
    marca: "Marca no identificada",
    tipo: "Joyas y relojes",
    foto: "photo-1535632787350-4e68ef0ac584",
    credito: U + "pair-of-silver-earring-lot-GKbfUFna-9I",
    valoracion: 4,
    opinion: "Para una fiesta, unos pendientes grandes de cristal sustituyen a cualquier collar. Con un vestido liso, son la única joya que hace falta.",
    combina: "Vestido negro o azul marino, pelo recogido y nada en el cuello.",
  },
  {
    slug: "collar-dorado-morado",
    nombre: "Collar dorado tradicional",
    marca: "Marca no identificada",
    tipo: "Joyas y relojes",
    foto: "photo-1601121141461-9d6647bca1ed",
    credito: U + "gold-and-purple-beaded-necklace-G3Hrl6WzQYQ",
    valoracion: 3,
    opinion: "Un collar dorado de inspiración india, muy trabajado. Precioso para una boda o una fiesta con escote; para el día a día es demasiado.",
    combina: "Vestido blanco de tirantes o camisa de lino abierta.",
  },
  {
    slug: "reloj-oro-rosa",
    nombre: "Reloj oro rosa",
    marca: "Marca no identificada",
    tipo: "Joyas y relojes",
    foto: "photo-1751437774882-deeea4352018",
    credito: U + "a-stylish-rose-gold-watch-rests-on-a-display-55ZjBmoOH1U",
    valoracion: 4,
    opinion: "El oro rosa es más cálido que el dorado y menos frío que el plateado: combina con casi cualquier tono de piel y con joyas de los dos colores.",
    combina: "Pulseras finas doradas, anillos sencillos. Con manga remangada para que se vea.",
  },
  {
    slug: "reloj-cronografo-acero",
    nombre: "Reloj cronógrafo de acero",
    marca: "Marca no identificada",
    tipo: "Joyas y relojes",
    foto: "photo-1549972574-8e3e1ed6a347",
    credito: U + "round-silver-colored-chronograph-watch-with-link-band-displaying-2-48-l1mVJnG7a84",
    valoracion: 3,
    opinion: "Un reloj de acero con esfera grande tiene presencia, pero en muñecas finas puede quedar pesado. Mejor probárselo antes que comprarlo por foto.",
    combina: "Camisa blanca, blazer y vaquero. Look de oficina con un toque masculino.",
  },
  // ───────────── Incorporaciones de septiembre de 2026 ─────────────
  {
    slug: "vestido-lencero-blanco-roto",
    nombre: "Vestido lencero blanco roto",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1702907644567-74f8f37bb068",
    credito: U + "a-white-shirt-hanging-on-a-rack-next-to-a-window-hHK0juTJ74o",
    valoracion: 5,
    opinion: "Tirante fino, caída recta y una tela que se mueve con la luz. Es el vestido que más partido saca por el precio que suele tener: de día con sandalia plana, de noche con tacón y ya está.",
    combina: "Sandalia de tiras dorada, chaqueta vaquera por los hombros si refresca y un bolso pequeño de piel natural.",
    destacada: true,
  },
  {
    slug: "vestido-blanco-escote-corazon",
    nombre: "Vestido blanco de escote corazón",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1540459920617-415d62f1f76b",
    credito: U + "white-sweetheart-neckline-dress-pHA6KL_HpoE",
    valoracion: 4,
    opinion: "El escote corazón favorece a casi todo el mundo y el largo por la rodilla lo hace útil más allá de una boda. Le quito una estrella porque el blanco puro es difícil de mantener.",
    combina: "Salón nude, pendientes pequeños y un chal ligero. Para bajarle el tono: zapatilla blanca y cazadora vaquera.",
  },
  {
    slug: "vestido-verde-menta-tirantes",
    nombre: "Vestido verde menta de tirantes",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1724891793770-49b41a5c9731",
    credito: U + "a-green-dress-hanging-on-a-clothes-rack-7tDTX5PU5mw",
    valoracion: 4,
    opinion: "Un verde suave que no se ve en todos los escaparates y una tela ligera con algo de textura. Es un vestido de verano sin pretensiones que se lleva puesto medio día sin pensar en él.",
    combina: "Sandalia plana de piel, cesta de rafia y gafas de sol negras. Un cinturón fino marrón marca la cintura si hace falta.",
  },
  {
    slug: "vestido-tweed",
    nombre: "Vestido de tweed",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1772909566980-b06731149511",
    credito: U + "a-tweed-dress-hangs-in-a-shop-window-display-pUcXzeGl04s",
    valoracion: 4,
    opinion: "El tweed pesa y por eso el vestido cae recto y no se pega. Es una pieza de entretiempo con aire francés que viste sola, sin accesorios. Ojo con el forro: si no lo lleva, pica.",
    combina: "Botín negro de tacón bajo, medias tupidas y una gabardina. Bolso de mano negro con cadena.",
  },
  {
    slug: "vestido-lencero-chocolate",
    nombre: "Vestido lencero chocolate",
    marca: "Marca no identificada",
    tipo: "Vestidos",
    foto: "photo-1652677481595-925d4e6be7d4",
    credito: U + "a-pair-of-shoes-and-a-shirt-hanging-on-a-rack-YX9-nFpr3sA",
    valoracion: 5,
    opinion: "El marrón chocolate es el negro de esta temporada: igual de fácil y más cálido con la piel. Un lencero en este color, con un poco de satén, vale para una cena y para un día de oficina con camisa debajo.",
    combina: "Camisa de cuadros abierta encima (como en la foto), mocasín y calcetín fino. De noche, sandalia de tacón y pendiente dorado.",
    destacada: true,
  },
  {
    slug: "abrigo-espiga-gris",
    nombre: "Abrigo de espiga gris",
    marca: "Marca no identificada",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1722858958066-97deb3471c89",
    credito: U + "a-coat-hanging-on-a-coat-rack-in-a-closet-pvCjWi5bATg",
    valoracion: 5,
    opinion: "Tejido de espiga, solapa ancha y largo por debajo de la rodilla: un abrigo de los de toda la vida. Si la mezcla lleva al menos la mitad de lana, es la compra del invierno.",
    combina: "Jersey de cuello vuelto crudo, vaquero recto y botín de piel. Con vestido negro y salón para la noche.",
    destacada: true,
  },
  {
    slug: "gabardina-amarilla",
    nombre: "Gabardina amarilla",
    marca: "Marca no identificada",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1565532070333-43edd7d75c90",
    credito: U + "hanged-yellow-coat-ibTHy8t7JvM",
    valoracion: 4,
    opinion: "Un chubasquero con corte de gabardina y un amarillo que alegra cualquier día gris. No es una prenda para pasar desapercibida; el resto del look tiene que ir en calma.",
    combina: "Todo en azul marino o vaquero: jersey marino, vaquero oscuro y zapatilla blanca. Nada más de color.",
  },
  {
    slug: "chaqueta-negra-lino",
    nombre: "Chaqueta negra de lino",
    marca: "Marca no identificada",
    tipo: "Abrigos y chaquetas",
    foto: "photo-1658418818804-adc6dc129ac2",
    credito: U + "a-black-jacket-on-a-white-wall-kNVl-jxS_X0",
    valoracion: 3,
    opinion: "Ligera, sin hombreras y con la arruga natural del lino. Está bien como capa de verano sobre un top, pero se deforma pronto en los bolsillos y no abriga nada.",
    combina: "Top blanco de tirantes, pantalón ancho crudo y sandalia plana. Bolso bandolera pequeño.",
  },
  {
    slug: "blusa-blanca-gasa",
    nombre: "Blusa blanca de gasa",
    marca: "Marca no identificada",
    tipo: "Camisas y tops",
    foto: "photo-1573675580296-266e838854f8",
    credito: U + "white-textile-on-rack-mQ158AIvL8w",
    valoracion: 4,
    opinion: "Transparente lo justo, con manga amplia y un cuello sencillo. La gasa se arruga menos que el algodón y viste más. Necesita un top liso debajo del mismo tono.",
    combina: "Vaquero de tiro alto, cinturón fino y salón. Por dentro del pantalón, siempre.",
  },
  {
    slug: "camisa-azul-marino-popelin",
    nombre: "Camisa azul marino de popelín",
    marca: "Marca no identificada",
    tipo: "Camisas y tops",
    foto: "photo-1620812112510-ea35f4cc7875",
    credito: U + "blue-button-up-long-sleeve-shirt-B1Le_4XqOS8",
    valoracion: 4,
    opinion: "Una camisa oscura sienta más seria que la blanca y disimula mejor el uso. En popelín de algodón cae recta y se plancha en un minuto. Mejor una talla más, para llevarla suelta.",
    combina: "Pantalón sastre gris, mocasín y reloj. Abierta sobre un vestido lencero también funciona.",
  },
  {
    slug: "camisa-lino-azul-cielo",
    nombre: "Camisa de lino azul cielo",
    marca: "Marca no identificada",
    tipo: "Camisas y tops",
    foto: "photo-1713881842156-3d9ef36418cc",
    credito: U + "a-blue-shirt-hanging-on-a-clothes-line-SI7Hmk8MXQU",
    valoracion: 5,
    opinion: "Manga corta, rayas finas y lino de verdad. Es la camisa de verano que se lleva arrugada sin complejos y que mejora con cada lavado. Un básico por el que merece la pena pagar tela buena.",
    combina: "Bermuda o pantalón blanco, sandalia Arizona y cesta. Anudada a la cintura sobre un vestido de tirantes.",
    destacada: true,
  },
  {
    slug: "jersey-marino-cuello-redondo",
    nombre: "Jersey marino de cuello redondo",
    marca: "Marca no identificada",
    tipo: "Punto",
    foto: "photo-1611312449545-94176309c857",
    credito: U + "black-crew-neck-sweater-on-white-clothes-hanger-rjsee9nKsYE",
    valoracion: 5,
    opinion: "Punto tupido, hombro caído y un azul casi negro que combina con todo. Es el jersey que se lleva de octubre a abril y no se nota. En lana o en mezcla con algodón, nunca en acrílico puro.",
    combina: "Vaquero claro, camisa blanca asomando por el cuello y zapatilla de piel. Con falda midi y botín también.",
  },
  {
    slug: "jersey-beige-canale",
    nombre: "Jersey beige de canalé",
    marca: "Marca no identificada",
    tipo: "Punto",
    foto: "photo-1744135994721-495cf9e87ede",
    credito: U + "a-white-sweater-hangs-on-a-gold-hanger--Ah6NPOCTvI",
    valoracion: 4,
    opinion: "El canalé fino se pega al cuerpo sin apretar y el beige es el color más fácil del armario después del negro. Un jersey que va igual de bien por dentro del pantalón que suelto.",
    combina: "Pantalón de pinzas marrón, cinturón de piel y mocasín. Con vaquero blanco en primavera.",
  },
  {
    slug: "jerseis-punto-grueso-tierra",
    nombre: "Jerséis de punto grueso en tonos tierra",
    marca: "Marca no identificada",
    tipo: "Punto",
    foto: "photo-1641642231157-0849081598a2",
    credito: U + "a-stack-of-sweaters-sitting-on-top-of-a-wooden-chair-jrQv0161nNM",
    valoracion: 4,
    opinion: "Un montón de jerséis de trenzas y ochos en crudo, camel y gris. Este punto grueso abriga como un abrigo ligero y aguanta años si es lana. Solo uno de estos por temporada: ocupan mucho.",
    combina: "Con vaquero recto y bota de agua o botín. Los tonos tierra piden un bolso marrón y nada de negro.",
  },
  {
    slug: "vaqueros-lavado-medio",
    nombre: "Vaqueros de lavado medio",
    marca: "Marca no identificada",
    tipo: "Vaqueros",
    foto: "photo-1721637286605-ae9be19d681f",
    credito: U + "a-pile-of-jeans-laying-on-top-of-each-other-XdXk39Bj3B0",
    valoracion: 4,
    opinion: "El lavado medio, ni muy claro ni muy oscuro, es el que más combina y el que menos pasa de moda. Buscad tela rígida con poca elastina: al principio incomoda y a los tres meses es el mejor vaquero del armario.",
    combina: "Camisa blanca, cinturón marrón y mocasín. Con jersey marino y zapatilla blanca es un uniforme.",
  },
  {
    slug: "vaquero-recto-parche-cuero",
    nombre: "Vaquero recto con parche de cuero",
    marca: "Marca no identificada",
    tipo: "Vaqueros",
    foto: "photo-1603202577997-003d15cfc20b",
    credito: U + "blue-denim-jeans-on-white-textile-HWEjIe7rc7w",
    valoracion: 4,
    opinion: "Pernera recta, tiro alto y el parche de cuero de siempre en la cintura. Es un corte clásico que estiliza sin estar apretado. El azul intenso pide lavarlo del revés y en frío.",
    combina: "Top negro ajustado, chaqueta de cuero y botín. De día, camiseta blanca y zapatilla.",
  },
  {
    slug: "bailarinas-burdeos-flor",
    nombre: "Bailarinas burdeos con flor",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1582738412120-7f6baeff4da9",
    credito: U + "red-and-silver-floral-flats-1MW0oT45Epo",
    valoracion: 3,
    opinion: "Terciopelo burdeos y un adorno de pedrería en la puntera: preciosas en la caja, delicadas en la calle. Para una cena o un evento sin tacón, sí; para el día a día, el terciopelo sufre.",
    combina: "Vestido negro liso o pantalón sastre negro tobillero. Nada más con adornos.",
  },
  {
    slug: "mocasin-gris-ante",
    nombre: "Mocasín gris de ante",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1678784973551-f38208de2529",
    credito: U + "a-pair-of-shoes-sitting-inside-of-a-box-avUyevopVlg",
    valoracion: 4,
    opinion: "El ante gris es más suave a la vista que el negro y combina con casi todo. El mocasín con antifaz se lleva con calcetín o sin él y aguanta el otoño entero. Un spray protector antes del primer uso.",
    combina: "Vaquero recto y calcetín blanco, o pantalón sastre gris y camisa. Con falda midi plisada también.",
  },
  {
    slug: "mocasin-marron-hebilla",
    nombre: "Mocasín marrón con hebilla",
    marca: "Marca no identificada",
    tipo: "Zapatos y botas",
    foto: "photo-1649503377051-e092f490c482",
    credito: U + "a-pair-of-shoes-sitting-on-top-of-a-table-PtyzHuwitng",
    valoracion: 5,
    opinion: "Piel marrón con brillo, hebilla dorada y suela de cuero. Es el zapato plano que más viste, punto. Duele una semana y después es para siempre.",
    combina: "Pantalón de pinzas, camisa y cinturón marrón a juego con la hebilla dorada. Con vaquero y jersey beige también.",
    destacada: true,
  },
  {
    slug: "canotier-paja",
    nombre: "Canotier de paja",
    marca: "Marca no identificada",
    tipo: "Accesorios",
    foto: "photo-1780850604969-bc9882d4164c",
    credito: U + "a-straw-hat-open-book-and-peaches-on-green-grass-HiKexx5qBgc",
    valoracion: 4,
    opinion: "Copa plana, ala corta y una cinta azul: el sombrero de verano que no parece disfraz. Protege menos que una pamela pero se lleva mejor en la ciudad.",
    combina: "Vestido lencero blanco, sandalia plana y cesta. Con camisa de lino y bermuda.",
  },
  {
    slug: "pamela-paja-ala-ancha",
    nombre: "Pamela de paja de ala ancha",
    marca: "Marca no identificada",
    tipo: "Accesorios",
    foto: "photo-1776722203359-3659e8f7a046",
    credito: U + "many-straw-hats-hanging-from-a-ceiling-FCJwug8fwhY",
    valoracion: 4,
    opinion: "Paja trenzada natural y ala grande: la pamela de playa de toda la vida, que sigue siendo la que mejor protege. Elegid una que se pueda enrollar sin romperse para meterla en la maleta.",
    combina: "Bañador liso, vestido largo de algodón y sandalia de cuero. Gafas de sol grandes.",
  },
  {
    slug: "bolso-azul-petroleo-solapa",
    nombre: "Bolso azul petróleo con solapa",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1594223274512-ad4803739b7c",
    credito: U + "blue-leather-handbag-on-black-leather-bag-nvQemFKRBUo",
    valoracion: 4,
    opinion: "Piel rígida, asa corta y un azul petróleo que funciona como neutro sin ser negro. Estructurado, de los que se quedan de pie solos. Cabe lo justo: móvil, cartera y llaves.",
    combina: "Gabardina beige, vaquero oscuro y mocasín. Con vestido negro y salón de noche.",
  },
  {
    slug: "bolso-trenzado-marron-sandalia-verde",
    nombre: "Bolso trenzado marrón y sandalia verde",
    marca: "Marca no identificada",
    tipo: "Bolsos",
    foto: "photo-1758178192200-aa46fa597e34",
    credito: U + "a-patterned-handbag-with-neon-green-slides-7RiNL2Ec4Rg",
    valoracion: 4,
    opinion: "Un bolso de piel trenzada en marrón, de los que envejecen bien, junto a una sandalia pala verde lima. La combinación es la lección: un neutro con textura y un solo golpe de color.",
    combina: "Vestido crudo o pantalón blanco, y que el único color sea la sandalia. Gafas de sol negras.",
  },

];

export function getPieza(slug: string) {
  return piezas.find((p) => p.slug === slug);
}
