// Marcas que aparecen en la barra en movimiento de la portada.
// Solo nombres (nombrar una marca es legal); nunca logotipos ni fotos suyas.
// Añade o quita marcas libremente: el orden es el de la barra.
export const marcas = [
  "Zara",
  "Springfield",
  "Mango",
  "Massimo Dutti",
  "H&M",
  "Stradivarius",
  "Bershka",
  "Pull&Bear",
  "Oysho",
  "Uterqüe",
  "Bimba y Lola",
  "Desigual",
  "Adolfo Domínguez",
  "Scalpers",
  "El Ganso",
  "Cortefiel",
  "Women'secret",
  "Parfois",
  "Lefties",
  "Primark",
  "Uniqlo",
  "COS",
  "& Other Stories",
  "Arket",
  "Sézane",
  "Levi's",
  "Nike",
  "adidas",
  "New Balance",
  "Converse",
  "Dr. Martens",
  "Birkenstock",
  "Ray-Ban",
  "Lacoste",
  "Tommy Hilfiger",
  "Michael Kors",
  "Coach",
  "Gucci",
  "Louis Vuitton",
] as const;
